# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 532)
        self.graphJointTorque = PlotWidget(Dialog)
        self.graphJointTorque.setGeometry(QtCore.QRect(410, 10, 250, 250))
        self.graphJointTorque.setObjectName("graphJointTorque")
        self.graphAbductionAdduction = PlotWidget(Dialog)
        self.graphAbductionAdduction.setGeometry(QtCore.QRect(410, 270, 250, 250))
        self.graphAbductionAdduction.setObjectName("graphAbductionAdduction")
        self.graphError = PlotWidget(Dialog)
        self.graphError.setGeometry(QtCore.QRect(930, 10, 250, 250))
        self.graphError.setObjectName("graphError")
        self.graphFlexionExtention = PlotWidget(Dialog)
        self.graphFlexionExtention.setGeometry(QtCore.QRect(670, 10, 250, 250))
        self.graphFlexionExtention.setObjectName("graphFlexionExtention")
        self.graphTransversalPlane = PlotWidget(Dialog)
        self.graphTransversalPlane.setGeometry(QtCore.QRect(670, 270, 250, 250))
        self.graphTransversalPlane.setObjectName("graphTransversalPlane")
        self.labelJointTorque = QtWidgets.QLabel(Dialog)
        self.labelJointTorque.setGeometry(QtCore.QRect(510, 10, 61, 16))
        self.labelJointTorque.setObjectName("labelJointTorque")
        self.labelFlexionExtention = QtWidgets.QLabel(Dialog)
        self.labelFlexionExtention.setGeometry(QtCore.QRect(750, 10, 91, 16))
        self.labelFlexionExtention.setObjectName("labelFlexionExtention")
        self.labelAbductionAdduction = QtWidgets.QLabel(Dialog)
        self.labelAbductionAdduction.setGeometry(QtCore.QRect(490, 270, 101, 16))
        self.labelAbductionAdduction.setObjectName("labelAbductionAdduction")
        self.labelTransversalPlane = QtWidgets.QLabel(Dialog)
        self.labelTransversalPlane.setGeometry(QtCore.QRect(750, 270, 91, 16))
        self.labelTransversalPlane.setObjectName("labelTransversalPlane")
        self.labelError = QtWidgets.QLabel(Dialog)
        self.labelError.setGeometry(QtCore.QRect(1050, 10, 47, 13))
        self.labelError.setObjectName("labelError")
        self.openGLWidget = QtWidgets.QOpenGLWidget(Dialog)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 10, 391, 511))
        self.openGLWidget.setObjectName("openGLWidget")
        self.pushButtonStart = QtWidgets.QPushButton(Dialog)
        self.pushButtonStart.setGeometry(QtCore.QRect(940, 280, 75, 23))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.pushButtonStop = QtWidgets.QPushButton(Dialog)
        self.pushButtonStop.setGeometry(QtCore.QRect(940, 310, 75, 23))
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.pushButtonClear = QtWidgets.QPushButton(Dialog)
        self.pushButtonClear.setGeometry(QtCore.QRect(940, 340, 75, 23))
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.teta1Slider = QtWidgets.QSlider(Dialog)
        self.teta1Slider.setGeometry(QtCore.QRect(960, 390, 160, 22))
        self.teta1Slider.setOrientation(QtCore.Qt.Horizontal)
        self.teta1Slider.setObjectName("teta1Slider")
        self.horizontalSlider_2 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(960, 430, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Shoulder Join Movement Model Simulation"))
        self.labelJointTorque.setText(_translate("Dialog", "Joint Torque"))
        self.labelFlexionExtention.setText(_translate("Dialog", "Flexion/Extention"))
        self.labelAbductionAdduction.setText(_translate("Dialog", "Abduction/Adduction"))
        self.labelTransversalPlane.setText(_translate("Dialog", "Transversal Plane"))
        self.labelError.setText(_translate("Dialog", "Error"))
        self.pushButtonStart.setText(_translate("Dialog", "Start"))
        self.pushButtonStop.setText(_translate("Dialog", "Stop"))
        self.pushButtonClear.setText(_translate("Dialog", "Clear"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
